### ISSUE TITLE
Wildcards Able to assign, but not cast in Lab 4 

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#89] opened 2020-09-24 04:05 UTC
Hello, in Lab 4, for the test case in the bonus level 
`Function<Object,Integer> f = x -> x.hashCode()
ImmutableList<Number> list = new ImmutableList<String>("one", "two", "three").map(f)`

Why is it that casting here would give an error? 
![lab4questioncasting](https://user-images.githubusercontent.com/10182564/94099179-e6274100-fe5c-11ea-8081-7881f7fcc609.png)

**Comment by SkyBlaise99** [comment] 2020-09-24 05:50
It's `Number` and not `Integer`.
[Number](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Number.html) is a superclass of Integer, hence you cannot cast `ImmutableList<Integer>` to `ImmutableList<Number>`

**Comment by tlylt** [comment] 2020-09-24 07:40
(P.S. Interesting Question!!!)
I suppose OP is asking what's the difference between
```java
Function<Object,Integer> f = x -> x.hashCode();
(ImmutableList<Number>) new ImmutableList<String>("one", "two","three").map(f);
```
And
```java
Function<Object,Integer> f = x -> x.hashCode();
ImmutableList<Number> list = new ImmutableList<String>("one", "two","three").map(f);
```
I was able to reproduce the error as shown. So I dig deeper...
### typecast
Ok `(ImmutableList<Integer>) new ImmutableList<String>("one", "two","three").map(f);`
Error `(ImmutableList<Number>) new ImmutableList<String>("one", "two","three").map(f);`
Error `(ImmutableList<Object>) new ImmutableList<String>("one", "two","three").map(f);`

### assignment
Ok `ImmutableList<Integer> list = new ImmutableList<String>("one", "two","three").map(f);`
Ok `ImmutableList<Number> list = new ImmutableList<String>("one", "two","three").map(f);`
Error `ImmutableList<String> list = new ImmutableList<String>("one", "two","three").map(f);`

The errors from typecast and assignment are slightly different.
The error when you type cast is 
```
incompatible types: ImmutableList<java.lang.Integer> cannot be converted to ImmutableList<java.lang.Number>
incompatible types: ImmutableList<java.lang.Integer> cannot be converted to ImmutableList<java.lang.Object>
```
The error when you assign is 
```
incompatible types: inference variable U has incompatible bounds, 
equality constraints: java.lang.String 
lower bounds: java.lang.Integer
```

---
My method header for the map function is as follows:
`public <U> ImmutableList<U> map(Function<? super T, ? extends U> f) {`

If the function supplied is `Function<Object,Integer> f = x -> x.hashCode();`
What do you think is `U` now ? `Object` or `Integer` or `Number` or ???

After discussion with my TA (Long :)), the way I understand the whole thing is as follows:

You have `<? super T, ? extends U>`, when you input the function f with `<Object, Integer> `, look at the part after the comma, `Integer` kind of goes into `?`, and `U` will be inferred by Java. How does it do the inference?
1. If output is being assigned to an `ImmutableList<Number>`, then `U` becomes `Number` (the type specified in the LHS of assignment)
2. If it is not assigned to anything, `U` becomes `Integer` ( U becomes the type in ?)

Then the error in typecasting is because
- the returned object is not being assigned to anything, hence can't infer from anywhere but the `?`, which is `Integer`.
- thus the returned object becomes `ImmutableList<Integer>`
- you cannot typecast it to `ImmutableList<Number>` due to invariance.

The error in assignment is because
- the returned object is assigned to `ImmutableList<String>`, so `U` infers to be `String`. 
- But, `<? extends U>` => `<Integer extends String>` is an incorrect statement.
- Hence, `incompatible types: inference variable U has incompatible bounds`

The reason why the other statements are correct should also be clear now. Hope this helps!

**Comment by Terence-Sim** [comment] 2020-09-24 07:52
Yes, very good reasoning!

**Comment by SkyBlaise99** [comment] 2020-09-24 08:19
Oh my bad, i did see the type cast, ignore my ans haha
But am I right on

> cannot cast `ImmutableList<Integer>` to `ImmutableList<Number>`

just that the reasoning is not `Number is a superclass of Integer` but
`ImmutableList<Number> is not a parent class of ImmutableList<Integer>`

**Comment by waynetee** [comment] 2020-09-24 09:03
@tlylt Nice post! I think this is a pretty interesting topic.

I think the process of the complier inferring the type is known as target typing, explained at the bottom of this page
[this page](https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html)

Also, this works!
`(ImmutableList<Number>) new ImmutableList<String>("one", "two","three").<Number>map(f);`

**Comment by tlylt** [comment] 2020-09-24 09:07
> Oh my bad, i did see the type cast, ignore my ans haha
> But am I right on
> 
> > cannot cast `ImmutableList<Integer>` to `ImmutableList<Number>`
> 
> just that the reasoning is not `Number is a superclass of Integer` but
> `ImmutableList<Number> is not a parent class of ImmutableList<Integer>`

I would say the reasoning is neither `Number is a superclass of Integer` nor 
`ImmutableList<Number> is not a parent class of ImmutableList<Integer>`.
Does whether `ImmutableList<Number>` is a "parent" class of `ImmutableList<Integer>` matter in anyway?
 
My reasoning will be `ImmutableList<Number> is not ImmutableList<Integer>`, hence due to invariance it does not compile.

**Comment by tlylt** [comment] 2020-09-24 09:32
@waynetee Interesting [read!](https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html)

Now armed with the "technical terms", I can rephrase some of my previous statements.

---
 ### Target Type & Type Witness
`ImmutableList<Number> list = new ImmutableList<String>("one", "two","three").map(f);`
- this statement (LHS) is expecting an instance of `ImmutableList<Number>`
- `ImmutableList<Number>` is the **target type**
- because the method map(f) returns a value of type `ImmutableList<U>`, the compiler infers that the type argument `U` must be the value `Number`
- alternatively, we can be explicit and state the **type witness**, right before the method name
`ImmutableList<Number> list = new ImmutableList<String>("one", "two","three").<Number>map(f);`

Also stated in the docs that the compiler will infer the target type from method arguments as well. 
I think our confusion is partly on the fact that our arguments are `< ? super U>`...

**Comment by SkyBlaise99** [comment] 2020-09-24 09:33
> Does whether ImmutableList<Number> is a "parent" class of ImmutableList<Integer> matter in anyway?

I mean isnt it like `Event = (Event) new ArriveEvent`? `Event` being the parent class of `ArriveEvent`.
So `ImmutableList<Number> = (ImmutableList<Number>) new ImmutableList<Integer>`? <- So does this works? I'm confused

Mb, I'm not familiar with github

**Comment by tlylt** [comment] 2020-09-24 09:35
> > Does whether ImmutableList is a "parent" class of ImmutableList matter in anyway?
> 
> I mean isnt it like Event = (Event) new ArriveEvent? Event being the parent class of ArriveEvent.
> So ImmutableList = (ImmutableList) new ImmutableList? <- So does this works? I'm confused

@SkyBlaise99 Can you put your code in \` \` so that the \< \> is not hidden?

**Comment by waynetee** [comment] 2020-09-24 09:38
I would say whether you can do `A a = b` depends on whether the class of b is a subtype of A.

For example `Animal[] animalArray = catArray` works because `Cat[]` is a subtype of `Animal[]` even though `Animal[]`, which is an array, is not a parent class of a cat array.

**Comment by SkyBlaise99** [comment] 2020-09-24 09:39
> I would say whether you can do A a = b depends on whether the class of b is a subtype of A.
>
> For example Animal[] animalArray = catArray works because Cat[] is a subtype of Animal[] even though Animal[], which is an array, is not a parent class of a cat array.

Oh ok, but A is a parent class of B right, like `Animal` is a parent class of `Cat`

**Comment by waynetee** [comment] 2020-09-24 09:42
Yes for animal being a parent class of cat, another example is List[] is not a parent class of ArrayList[] but you can do List[] a = new ArrayList[2]

**Comment by tlylt** [comment] 2020-09-24 09:49
> `ImmutableList<Number> = (ImmutableList<Number>) new ImmutableList<Integer>`

@SkyBlaise99 
There is one obvious mistake in your statement, probably by carelessness...
you need to have (), i.e. `new ImmutableList<Integer>();`

If you haven't got the chance to try this in Jshell, I encourage you to think of the following questions:
- if it doesn't work, which part of the statement is causing the error?
- what error is it going to be? the first type or the second type, the error for typecast or the error for assignment (referring to my previous answer)?

**Comment by FergusMok** [comment] 2020-09-24 14:25
Thanks alot everyone, it's much clearer now. I wasn't sure what to google previously too haha

**Closed as completed** 2020-09-24 14:26 UTC
Labels: :computer_mouse: Java
