### ISSUE TITLE
Project 1 level 4 test 3

### ISSUE THREAD

**Issue by charoi** [nus-cs2030/2021-s1#111] opened 2020-09-29 11:27 UTC
# Description 
Regarding test case and actual result I produced, I ran into a line where I felt on code crunch, when 4 waits for 1, customer 4 gets served later than if 4 waits for 2, where customer 4 gets served at time = 1.6  instead of time = 2.5 as seen later on. As I was looking thru, it occurred that average wait time was also shorter, and 2 had no waiting customers at time of arrival of 4 (time = 1.5). So why is it wrong for server 4 to wait for 2?
Is there something I am not considering? Im really stuck in the last test case because of this...

![testcase vs actual](https://user-images.githubusercontent.com/41200981/94552616-bbd4e980-0289-11eb-92c0-eb6cd11210c0.png)

**Comment by enqiilim** [comment] 2020-09-29 11:36
could be when the previous waiting customer 3 is served by 1, you did not update that the server 1 does not have waiting customer

**Comment by aaron-ljx** [comment] 2020-09-29 11:46
I think the bigger problem here is at 2.500 where both 5 and 6 are served by 1. Maybe if you fix that problem, your other problems might be fixed as well.

**Comment by darrenhoon** [comment] 2020-09-29 11:59
just a hunch (since I just got this done today too), probably the issue is at how you let your customer "pick" the server, which suggests the error is either in the server's values and specifically Server 1's values not being edited correctly (assuming the logic for assignment of customer to server is correct), or the logic for the assignment of customer to server is wrong (assuming the values for the Servers are edited correctly)

**Comment by marcuspeh** [comment] 2020-09-29 11:59
What u did is technically correct but what the question wanted is that the customer will not know whats the fastest queue. So the customer should be assigned to the first server that it can queue instead of the shortest wait time

**Comment by guccilerino** [comment] 2020-09-29 12:14
I had the same issue but i think the question wants it such that the customer is assigned to an avail server of a smaller id

**Comment by zzkzzzz** [comment] 2020-09-29 12:16
According to the project description, if there is no free server, the customer will scan the server list, from the first one to the last one, and waits at the first busy server without a waiting customer. I think what you did is scan the server list, find the shortest waiting time busy server without a waiting customer. The simulator is not that "smart" haha.

**Comment by ramapriyan912001** [comment] 2020-09-29 15:33
Think of it like a queue at McDonalds. 
You dont all stand in one line and get assigned to the first free cashier (server).
You go and stand in an individual server queue, and then get served by the cashier when your time comes.
Something similar here.
Kinda shows how inefficient the world is to be honest haha.

**Closed as completed** 2020-09-30 23:55 UTC
Labels: :computer_mouse: Java
